// <auto-generated />
using System;
using ESP.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ESP.Infrastructure.Comment", b =>
                {
                    b.Property<int>("IdComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComment"));

                    b.Property<string>("Comment1")
                        .HasColumnType("text")
                        .HasColumnName("Comment");

                    b.Property<int>("IdRace")
                        .HasColumnType("int(11)");

                    b.Property<int>("Rate")
                        .HasColumnType("int(11)");

                    b.HasKey("IdComment")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRace" }, "IdRace");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("ESP.Infrastructure.Race", b =>
                {
                    b.Property<int>("IdRace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRace"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdRaceType")
                        .HasColumnType("int(11)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Kilometer")
                        .HasColumnType("int(11)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NumberPlace")
                        .HasColumnType("int(11)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRace")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRaceType" }, "IdRaceType");

                    b.ToTable("Races", (string)null);
                });

            modelBuilder.Entity("ESP.Infrastructure.Racetype", b =>
                {
                    b.Property<int>("IdRaceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRaceType"));

                    b.Property<string>("RaceType1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RaceType");

                    b.HasKey("IdRaceType")
                        .HasName("PRIMARY");

                    b.ToTable("Racetypes", (string)null);
                });

            modelBuilder.Entity("ESP.Infrastructure.Registration", b =>
                {
                    b.Property<int>("IdRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRegistration"));

                    b.Property<int>("BibNumber")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdRace")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int(11)");

                    b.HasKey("IdRegistration")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRace" }, "IdRace")
                        .HasDatabaseName("IdRace1");

                    b.HasIndex(new[] { "IdUser", "IdRace" }, "IdUser")
                        .IsUnique();

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("ESP.Infrastructure.Result", b =>
                {
                    b.Property<int>("IdResult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResult"));

                    b.Property<int>("IdRace")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int(11)");

                    b.Property<int>("Place")
                        .HasColumnType("int(11)");

                    b.HasKey("IdResult")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRace" }, "IdRace")
                        .HasDatabaseName("IdRace2");

                    b.HasIndex(new[] { "IdUser", "IdRace" }, "IdUser")
                        .IsUnique()
                        .HasDatabaseName("IdUser1");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("ESP.Infrastructure.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ClubTeam")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdUser")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Mail" }, "Mail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ESP.Infrastructure.Comment", b =>
                {
                    b.HasOne("ESP.Infrastructure.Race", "IdRaceNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdRace")
                        .IsRequired()
                        .HasConstraintName("comments_ibfk_1");

                    b.Navigation("IdRaceNavigation");
                });

            modelBuilder.Entity("ESP.Infrastructure.Race", b =>
                {
                    b.HasOne("ESP.Infrastructure.Racetype", "IdRaceTypeNavigation")
                        .WithMany("Races")
                        .HasForeignKey("IdRaceType")
                        .IsRequired()
                        .HasConstraintName("races_ibfk_1");

                    b.Navigation("IdRaceTypeNavigation");
                });

            modelBuilder.Entity("ESP.Infrastructure.Registration", b =>
                {
                    b.HasOne("ESP.Infrastructure.Race", "IdRaceNavigation")
                        .WithMany("Registrations")
                        .HasForeignKey("IdRace")
                        .IsRequired()
                        .HasConstraintName("registrations_ibfk_2");

                    b.HasOne("ESP.Infrastructure.User", "IdUserNavigation")
                        .WithMany("Registrations")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("registrations_ibfk_1");

                    b.Navigation("IdRaceNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ESP.Infrastructure.Result", b =>
                {
                    b.HasOne("ESP.Infrastructure.Race", "IdRaceNavigation")
                        .WithMany("Results")
                        .HasForeignKey("IdRace")
                        .IsRequired()
                        .HasConstraintName("results_ibfk_2");

                    b.HasOne("ESP.Infrastructure.User", "IdUserNavigation")
                        .WithMany("Results")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("results_ibfk_1");

                    b.Navigation("IdRaceNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ESP.Infrastructure.Race", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Registrations");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("ESP.Infrastructure.Racetype", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("ESP.Infrastructure.User", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
