name: Deploy on Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      
      - name: Deploy to Server
        env:
          USER_VM: ${{ secrets.USER_VM }}
          IP_VM: ${{ secrets.IP_VM }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER_VM@$IP_VM "
            set -e
            rm -rf /var/www/ESP/ESP-API
            mkdir -p /var/www/ESP/ESP-API
            cd /var/www/ESP/ESP-API

            git clone https://github.com/ESP-H26-Edgar/ESP-API.git .
                        
            git fetch origin main
            git reset --hard origin/main
            
            dotnet restore
            dotnet publish -c Release -o /var/www/ESP/ESP-API/publish
            cp /var/www/ESP/appsettings.json /var/www/ESP/ESP-API/publish/appsettings.json
            cp /var/www/ESP/.env /var/www/ESP/ESP-API/publish/.env
            
            # Redémarrer le service systemd
            sudo systemctl restart esp-api
            
          "
